// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQF0Fk4FfTHxrbgVVIYOkeqb3onU6QWs',
    appId: '1:151093699353:web:006a8242c9474bd3329b88',
    messagingSenderId: '151093699353',
    projectId: 'midyear-nebula-325210',
    authDomain: 'midyear-nebula-325210.firebaseapp.com',
    storageBucket: 'midyear-nebula-325210.appspot.com',
    measurementId: 'G-M54PFYTBM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5iYgm1-kTrRI9EPNc6MH_S_4Kd493JU0',
    appId: '1:151093699353:android:38ed239f28cf8cf2329b88',
    messagingSenderId: '151093699353',
    projectId: 'midyear-nebula-325210',
    storageBucket: 'midyear-nebula-325210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgRx0CnafjVDF8yPlIntbwCIs2rkZDc7U',
    appId: '1:151093699353:ios:bffda53552402f02329b88',
    messagingSenderId: '151093699353',
    projectId: 'midyear-nebula-325210',
    storageBucket: 'midyear-nebula-325210.appspot.com',
    iosClientId: '151093699353-akbrk9spkj9ovaklqj5ptjsk1nuv2nq8.apps.googleusercontent.com',
    iosBundleId: 'com.test.app',
  );
}
